config/routes.rb
Rails.application.routes.draw do

  resources :galleries, only: [ :index, :show ] do
    resources :reviews, only: :create
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#home'
  get 'mainpage' => 'pages#mainpage'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :gallery
  validates :content, length: {minimum: 20}
  validates :gallery, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :galleries

  after_create :send_welcome_email

   def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def name
    email #fine hott #{first_name}, #{last_name}
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/Users/Omniauth_Callbacks_Controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      flash[:alert] = "Provide email address"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    @review = Review.new  # <-- You need this now.
  end


  # GET /galleries/new
  def new
    @gallery = current_user.galleries.build
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = current_user.galleries.build(gallery_params)

      if @gallery.save
        GalleryMailer.creation_confirmation(@gallery).deliver_now
       redirect_to @gallery, notice: 'Gallery was successfully created.'
      else
        render :new
      end

  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :mainpage
  def home
  end

  def mainpage
  end

  def galleries
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @gallery = Gallery.find(params[:gallery_id])
    @review = Review.new(review_params)
    @review.gallery = @gallery
    if @review.save
      redirect_to gallery_path(@gallery)
    else
      render 'galleries/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      flash[:alert] = "Provide email address"
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/galleries/_form.html.erb
<%= simple_form_for(@gallery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <!--<%= f.association :user %> -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%=gallery.user.email %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', galleries_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @gallery.user %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

<h1><%= @gallery.name %></h1>
<h2>
  <%= pluralize @gallery.reviews.size, "review" %>
</h2>


<div id="reviews">
  <% if @gallery.reviews.blank? %>
    Be the first to leave a review for <%= @gallery.name %>
  <% else %>
    <% @gallery.reviews.each do |review| %>
    <%= render 'reviews/form', gallery: @gallery, review: @review %>
     <!--  <%= render 'reviews/show', review: review %> -->
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OCTOPUS</title>
    <link rel="shortcut icon" href="http://www.hostinsight.com/assets/layout/octopus.png" type="image/png"/>


    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- <meta name = "format-detection" content = "telephone=no"> -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container" >
      <div class="row">
        <div class="col-sm-6.col-sm-offset-3">
             <%= yield %>
        </div>
      </div>
    </div>



    <%= render 'shared/footer'%>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="maindiv">

  <img src="http://www.hostinsight.com/assets/layout/octopus.png"></img>

  <h1>OCTOPUS LAND</h1>
  <p>The Team Work Makes The Dream Work</p>

</div>

app/views/pages/mainpage.html.erb
<div id="mainpage" class="text-center">

  <h1>welocme to octopus</h1>
  <p>An unforgetable experience awaiting discovery</p>

</div>

app/views/reviews/_from.html.erb
<%= simple_form_for([ gallery, review ]) do |form| %>
  <%= form.input :content %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p>
  <%= review.content %>
</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="col-xs-12 text-center" id="footer">
  <ul class="list-inline">
    <li><a href=""><i class="fa fa-youtube"></i></a></li>
    <li><a href=""><i class="fa fa-instagram"></i></a></li>
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-twitter"></i></a></li>
  </ul>

  © 2015 - OCTOPUS - Beirut, Lebanon, Tel: 00961 1 123456
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-octopus">
  <div class="container navbar-octopus-container">

    <%= link_to "/" do %>
      <%= image_tag "http://www.hostinsight.com/assets/layout/octopus.png", class: "navbar-octopus-logo" %>
    <% end %>

    <div class="navbar-octopus-pusher"></div>

    <form action="" class="navbar-octopus-search hidden-xs hidden-sm">
      <input type="text" class="navbar-octopus-search-input" placeholder="Search something">
      <button type="submit" class="navbar-octopus-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-octopus-item navbar-octopus-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-octopus-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-octopus-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-octopus-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-octopus-item navbar-octopus-link" %>
       <%# link_to "Sign in with Facebook", omniauth_authorize_path('user', 'facebook' ), class: "navbar-octopus-item navbar-octopus-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "/mainpage", class: "navbar-octopus-item navbar-octopus-button btn" %>
  </div>
</nav>